name: Export job 
on:
  push:
    paths:
      - 'dynamo-s3.yml'
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file dynamo-s3.yml \
            --stack-name receeve-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
